application/models.py
from application import db

class Speeches(db.Model):
    __tablename__ = "speeches"
    __table_args__ = {'extend_existing': True}
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=True)
    date_s = db.Column(db.DateTime)
    speech = db.Column(db.Text, nullable=True)
    url = db.Column(db.String(200), nullable=True)
    len_s = db.Column(db.Integer, nullable=True)
    time_s = db.Column(db.Integer, nullable=True)

    def __repr__(self):
        return "<President %r>" % self.name

application/__init__.py
from flask import Flask
import csv
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config.from_object("config.Config")

    db.init_app(app)

    with app.app_context():
        from . import routes

        app.register_blueprint(routes.main_bp)

        db.create_all()

    return app

application/routes.py
from flask import Blueprint, render_template, url_for, request
from application import db
from .models import Speeches 
import sys
import csv
import datetime

main_bp = Blueprint("main", __name__)

def _fill_db(data):
    for item in data:
        db.session.add(
            Speeches(
                name = item["name"],
                date_s = datetime.datetime.strptime(item["date"], "%Y-%m-%d"),
                speech = item["speech"],
                url = item["url"],
                len_s = item["len_s"],
                time_s = item["time_s"]
            )
        )
    db.session.commit()

def _read_csv():
    csv.field_size_limit(sys.maxsize)
    with open("all_speeches_20201024.csv") as file:
        csv_reader = csv.reader(file)
        speech_dict = {}
        speech_list = []
        flag = True
        for speech in csv_reader:
            if flag:
                flag = False
            else:
                speech_dict["name"] = speech[1]
                speech_dict["date"] = speech[2]
                speech_dict["speech"] = speech[3]
                speech_dict["url"] = speech[4]
                speech_dict["len_s"] = speech[5]
                speech_dict["time_s"] = speech[6]
                speech_list.append(speech_dict.copy())
    return speech_list


@main_bp.route("/", methods = ["GET"])
def index():
    presidents = Speeches.query.group_by(Speeches.name)
    return render_template("index.html", queries=presidents)


@main_bp.route("/<president>", methods=["GET"])
def analyze(president):
    if president == "all":
        try:
            all_predidents = Speeches.query.all()
        except:
            return "ERROR en la Consulta!"
        q = request.args.get("q")
        result = {}
        all_results = []
        total = 0
        for president in all_predidents:
            match = president.speech.count(q.lower())
            if match > 0:
                result["count"] = int(match)
                result["name"] = president.name
                result["url"] = president.url
                result["date"] = president.date_s.strftime("%b %d, %Y")
                total = total + match
                all_results.append(result.copy())

        temp = {}
        total_by_presi = [] 
        p_list = set([ item["name"] for item in all_results ]) 
        for i in p_list:
            temp["total"] = sum([ item["count"] for item in all_results if i == item["name"] ])
            temp["name"] = i
            total_by_presi.append(temp.copy())

        return render_template("analyze.html", all_results=all_results, total=total, word=q.lower(), total_by_presi=total_by_presi)

application/templates/analyze.html
{% extends "base.html" %}

{% block content %}
    <section class="my-2">
        <ul class="nav">
            <li class="nav-item">
            Select a country: &nbsp;
            </li>
            <li class="nav-item">
            🇺🇸
            </li>
        </ul>
    </section>
    <section>
        <form action="{{ url_for('main.analyze', president='all', q=q) }}" method="GET">
            <div class="input-group mb-3">
            <input type="text" class="form-control" aria-label="Text input with checkbox" placeholder="Analyzes a word..." name="q">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Search!</button>
            </div>
            </div>
        </form>
    </section>
    <hr>
    <div class="card text-white bg-secondary mb-3">
        <div class="card-body">
          <h5 class="card-title text-center" style="margin-bottom: 0;"">The Presidents said "{{ word }}" <b>{{ total }}</b> times</h5> 
        </div>
      </div>      
    <div class="card-columns">
        {% for name, result in all_results|groupby("name") %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ name }}</h5>
                        {% for p_name in total_by_presi %}
                            {% if p_name.name == name %}
                                <p class="card-text">Said it <b>{{ p_name.total}}</b> times total</p>
                            {% endif %}
                        {% endfor %}
                        <ul>
                            {% for item in result %}
                                    <li>On <a href="{{ item.url }}" target="_blank"> {{ item.date }}</a> said it {{ item.count }} times.</li>
                            {% endfor %}
                        </ul>
                </div>
            </div> 
        {% endfor %}
    </div>
{% endblock %}

application/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='styles/styles.css')}}">

    <title>What you said Mr President?</title>
  </head>
  <body>
    <main class="container wrapper">
        {% block content %}{% endblock %}
    </main>
    <footer>
      <div class="text-center bg-dark py-4">
        <small>
          <p class="text-muted">Made with 🤘🏽 from 🇻🇪 by <a class="text-reset" href="http://borisaavedra.com" target="_blank">Borisaavedra</a></p>
        </small>
      </div>
    </footer>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

application/templates/index.html
{% extends "base.html" %}

{% block content %}
    <header>
      <div class="jumbotron jumbotron-fluid mt-4">
          <div class="container">
          <h1 class="display-4">👨‍💼 What you said Mr President?</h1>
          <p class="lead">Tiny speech analyzer to find out what the most powerful politicians said</p>
          <hr class="my-4">
          <p class="text-muted">
            <small>
              All US presidents speeches were scraped from <a href="https://millercenter.org/the-presidency/presidential-speeches" target="_blank" rel="noopener noreferrer">Miller Center</a><br>
              <i>Last update: Oct, 25 2020</i>
            </small>
          </p>
          </div>
      </div>
    </header>
    <section class="mb-2">
        <ul class="nav">
            <li class="nav-item">
              Select a country: &nbsp;
            </li>
            <li class="nav-item">
              🇺🇸
            </li>
          </ul>
    </section>
    <section>
      <form action="{{ url_for('main.analyze', president='all', q=q) }}" method="GET">
        <div class="input-group mb-3">
          <input type="text" class="form-control" aria-label="Text input with checkbox" placeholder="Analyzes a word..." name="q">
          <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit">Search!</button>
          </div>
        </div>
      </form>
    </section>
    <!-- <section>
      <div class="container">
        <h2>Presidents</h2>
        <div class="row row-cols-4 mx-auto">
          {% for query in queries %}
                <div class="col">
                  <div class="card mb-2">
                    <div class="body-card" for="president-check">
                       {{ query.name }}
                    </div>
                  </div>
                </div>
            {% endfor %}
        </div>
    </section> -->

    

{% endblock %}